platform :ios ,'8.0'
use_frameworks!

target 'MBBS' do

pod 'MJExtension'

pod 'SDWebImage', '~>3.7'

pod 'AFNetworking', '~> 3.0'

pod 'MBProgressHUD', '~> 0.9.2'

pod 'MJRefresh'

pod 'FDFullscreenPopGesture', '1.1'

pod 'SVProgressHUD'

pod 'DACircularProgress', '~> 2.3.1'

pod 'pop', '~> 1.0'

#[!] xcodeproj was renamed to `project`. Please use that from now on.
project 'MBBS.project'

end 

